### ISSUE TITLE
Prompt isn't always loaded

### ISSUE THREAD

**Issue by one-some** [henk717/KoboldAI-Client#258] opened 2023-01-13 00:45 UTC
Sometimes, the prompt isn't loaded, but the rest of the actions are. Reloading the page fixes this.

**Comment by ebolam** [comment] 2023-04-27 14:51
This is fixed in PR #333. We now refresh the browser on loading a story :). Error was caused by a race condition between the server sending data and the browser clearing existing data.

**Closed as completed** 2023-04-27 15:12 UTC
